In [94]:
import pandas as pd
import numpy as np
import random

In [78]:
names = pd.read_csv('transaction.csv')['name']
names = pd.DataFrame(list(set(names)), columns=['name'])
transaction = pd.read_csv('transaction.csv')

In [97]:

salaryList= []
for i in range(names.shape[0]):
#     if i %1000 == 0: print('zx')
    name = names.iloc[i]['name']
    total = sum(transaction.loc[transaction['name'] == name, 'amount'])
    percentage = random.randrange(-10,1000)
    
    total += total * (percentage/100.0)
    
#     print(total, percentage)
    salaryList.append(total)
    
    
names['salary'] = salaryList
names

6850.57
7691.56
5778.45
6526.77
6910.46
6383.46
6276.97
6069.86
6187.87
6465.4
5868.83
6454.58
6420.66
5862.06
5714.79
5760.78
5000.39
5981.03
6311.93
6398.43
6803.64
5505.19
7037.89
6280.84
6630.31
7104.74
6612.28
6359.4
5194.1
6177.33
5374.54
6472.76
5188.95
5884.53
6634.66
5329.52
5856.25
5852.19
6301.76
6162.15
5061.47
5883.98
5913.59
6112.56
4997.72
7599.85
5806.21
5534.34
6518.68
5967.46
6075.78
6139.85
6342.94
7046.36
5163.77
5576.82
6282.09
6117.9
6060.1
6169.41
5988.54
5193.09
6154.53
6073.16
6962.45
6907.18
5278.04
5456.66
5305.04
6815.46
5229.32
6404.23
5382.21
5328.37
6218.74
6037.46
5958.81
5882.48
6231.49
5964.39
6525.99
6235.15
6701.99
6862.59
6612.63
5819.2
6789.75
5880.3
5912.16
5638.11
6310.29
6097.79
7271.29
5240.19
6579.94
6583.76
6325.5
6453.63
6303.03
6444.34
6454.43
6123.23
6205.62
5931.92
6352.98
5565.03
5706.61
6644.55
7100.69
6283.71
5362.86
5986.27
6392.98
6564.87
6857.1
6601.97
5654.11
5133.13
5563.14
6310.09
5909.07
5815.36
5879.69
6276.89
5872.65
5648.39
6179.53
6610.01
6995.77
5899.73
6741.72
5808.61
6471.82
5445.4
5739.84
6628.14
6677.42
6330.12
6320.8
6333.49
5341.06
6285.1
5604.48
5882.35
7328.84
5915.9
5520.57
6136.33
6886.76
7213.61
7019.03
6512.55
5436.54
7427.01
6959.76
6735.05
5416.61
6782.67
6200.51
6314.6
4932.22
5215.03
6415.82
6321.68
6268.75
6989.92
6218.19
6623.52
6308.84
7061.8
6898.62
5839.47
6151.76
6129.02
6080.16
6759.22
6836.71
6918.1
6223.98
5638.41
6997.76
5832.77
5822.9
5895.89
6084.17
5875.02
4894.7
6884.22
6038.96
5578.21
6593.63
6592.88
6109.18
6549.44
6299.65
5421.6
5515.63
6110.8
6314.6
5935.72
6341.26
6014.99
6565.02
5967.44
5795.7
6744.86
6444.82
6838.81
6562.84
6502.31
6289.38
7265.24
6239.29
6373.52
5932.15
6023.37
5870.3
6862.54
6182.59
6301.33
6970.48
6095.87
5151.27
5649.58
6500.37
6061.47
6131.9
7298.93
5494.49
6638.23
6492.6
5068.74
6061.9
6224.28
6060.02
5941.0
6050.38
5856.3
6883.78
6318.69
6323.42
6006.74
6954.23
6458.01
5549.58
5761.94
6238.57
6338.94
4964.14
6278.48
6003.55
6480.02
6725.2
6614.31
6406.45
6959.13
6380.72
5950.23
5365.7
5869.63
6432.5
6019.86
5768.77
6426.5
6057.44
6630.99
6682.06
6752.14
4968.0
6865.05
6112.5
6448.89
6786.73
5589.3

KeyboardInterrupt:

In [89]:
for i in range(names.shape[0]):
    names.iloc[i]['salary']

ValueError: Length of values does not match length of index

In [68]:
transaction = pd.read_csv('transaction.csv')
transaction

,time,name,gender,age,company name,company label,amount
0,2017-07-02 22:27:48,Rachel Trujillo,male,36,Coursera Inc.,Education,111.22
1,2017-06-10 12:37:05,Rachel Trujillo,male,36,Laura Mercier Cosmetics.,Beauty,108.46
2,2017-06-07 14:24:02,Rachel Trujillo,male,36,Synovus Financial Corp.,Investment,208.21
3,2017-06-25 15:36:22,Rachel Trujillo,male,36,Peak Tramways Company Limited,Transport,222.79
4,2017-06-30 03:34:48,Rachel Trujillo,male,36,McDonald' s,Dining,86.28
5,2017-06-29 18:00:00,Rachel Trujillo,male,36,Pearson plc,Education,47.68
6,2017-06-30 21:34:26,Rachel Trujillo,male,36,Wal-Mart Stores Inc,Grocery,93.69
7,2017-07-04 11:57:56,Rachel Trujillo,male,36,Principal Financial Group Inc,Investment,115.46
8,2017-06-13 06:54:58,Rachel Trujillo,male,36,"Voya Financial, Inc.",Investment,142.11
9,2017-07-02 18:23:56,Rachel Trujillo,male,36,"The Dairy Farm Company, Limited",Grocery,61.87
10,2017-06-17 03:32:26,Rachel Trujillo,male,36,"2U, Inc.",Education,280.35
11,2017-07-03 13:44:19,Rachel Trujillo,male,36,City Super Limited,Grocery,281.82
12,2017-06-16 16:16:17,Rachel Trujillo,male,36,GAP,Clothing,9.13
13,2017-06-17 01:17:02,Rachel Trujillo,male,36,Subway,Dining,104.77
14,2017-06-21 11:14:37,Rachel Trujillo,male,36,"KOKUYO Co.,Ltd.",Stationery,300.88
15,2017-06-11 21:15:08,Rachel Trujillo,male,36,"Raymond James Financial, Inc.",Investment,33.22
16,2017-06-14 11:45:03,Rachel Trujillo,male,36,"KOKUYO Co.,Ltd.",Stationery,297.04
17,2017-07-03 21:29:17,Rachel Trujillo,male,36,Liberty Stationery Corp.,Stationery,133.08
18,2017-06-20 09:04:47,Rachel Trujillo,male,36,Ikari Area,Entertainment,9.43
19,2017-06-10 18:31:22,Rachel Trujillo,male,36,"The 'Star' Ferry Company, Limited",Transport,201.96
20,2017-07-05 20:58:23,Rachel Trujillo,male,36,Tim Ho Wan,Dining,292.67
21,2017-06-23 20:15:43,Rachel Trujillo,male,36,BB Liquidating Inc,Media,163.39
22,2017-06-24 15:32:14,Rachel Trujillo,male,36,Parker Pen Company,Stationery,260.15
23,2017-06-24 04:00:43,Rachel Trujillo,male,36,Le.com,Media,149.06
24,2017-07-04 03:13:19,Rachel Trujillo,male,36,J. Crew,Clothing,273.85
25,2017-06-12 00:30:44,Rachel Trujillo,male,36,"Voya Financial, Inc.",Investment,93.04
26,2017-06-20 09:50:33,Rachel Trujillo,male,36,Neway Karaoke Box Limited,Entertainment,239.05
27,2017-06-22 22:08:41,Rachel Trujillo,male,36,TCF Financial Corporation,Investment,244.24
28,2017-06-11 13:26:35,Rachel Trujillo,male,36,Principal Financial Group Inc,Investment,117.48
29,2017-07-04 09:40:59,Rachel Trujillo,male,36,Laura Mercier Cosmetics.,Beauty,134.45
...,...,...,...,...,...,...,...
399970,2017-06-12 23:41:20,Kelsey Jones,male,50,Sumitomo Mitsui Financial Group Inc,Investment,16.89
399971,2017-06-29 22:55:52,Kelsey Jones,male,50,"Udacity, Inc.",Education,197.18
399972,2017-06-08 21:36:12,Kelsey Jones,male,50,Staedtler Mars GmbH & Co. KG,Stationery,81.63
399973,2017-06-07 07:32:09,Kelsey Jones,male,50,"Waddell & Reed Financial, Inc.",Investment,258.03
399974,2017-06-30 10:49:34,Kelsey Jones,male,50,"Shenzhen Comix Stationery Co., Ltd.",Stationery,200.22
399975,2017-06-29 10:25:22,Kelsey Jones,male,50,Hong Kong Dragon Airlines Ltd,Transport,16.32
399976,2017-07-02 23:05:33,Kelsey Jones,male,50,Maxim' s Catering,Dining,265.12
399977,2017-06-14 09:14:25,Kelsey Jones,male,50,Shinhan Financial Group Co Ltd,Investment,113.96
399978,2017-06-16 23:01:34,Kelsey Jones,male,50,The Kowloon Motor Bus Company Limited,Transport,51.15
399979,2017-06-30 20:05:53,Kelsey Jones,male,50,Xbox,Entertainment,233.69
399980,2017-06-14 11:43:47,Kelsey Jones,male,50,J. Crew,Clothing,141.99
399981,2017-06-07 09:19:46,Kelsey Jones,male,50,New World First Bus Services Limited,Transport,197.35
399982,2017-06-28 11:42:38,Kelsey Jones,male,50,edX Inc.,Education,294.94
399983,2017-06-13 14:28:37,Kelsey Jones,male,50,Yadkin Financial Corporation,Investment,52.28
399984,2017-06-17 13:29:12,Kelsey Jones,male,50,"Netflix, Inc.",Media,31.73
399985,2017-06-15 06:16:08,Kelsey Jones,male,50,Ikari Area,Entertainment,201.77
399986,2017-06-23 18:05:50,Kelsey Jones,male,50,Levi Strauss & Co.,Clothing,272.93
399987,2017-06-16 12:47:34,Kelsey Jones,male,50,Spotify AB,Media,114.97
399988,2017-06-22 20:57:56,Kelsey Jones,male,50,Cathay Pacific Airways,Transport,71.12
399989,2017-06-26 04:56:07,Kelsey Jones,male,50,Coursera Inc.,Education,275.30
399990,2017-07-02 17:11:21,Kelsey Jones,male,50,Code School LLC.,Education,92.36
399991,2017-06-16 02:28:35,Kelsey Jones,male,50,Ryze Ultimate Trampoline Park Hong Kong,Entertainment,283.62
399992,2017-07-04 20:10:37,Kelsey Jones,male,50,"Redbox Automated Retail, LLC.",Media,169.40
399993,2017-06-17 02:49:32,Kelsey Jones,male,50,McDonald' s,Dining,55.72
399994,2017-06-28 08:49:46,Kelsey Jones,male,50,Long Win Bus Company Limited,Transport,156.04
399995,2017-07-02 21:33:10,Kelsey Jones,male,50,New Oriental Education & Tech Grp,Education,39.57
399996,2017-06-26 10:09:42,Kelsey Jones,male,50,Xbox,Entertainment,222.35
399997,2017-06-13 04:40:07,Kelsey Jones,male,50,Tim Ho Wan,Dining,163.53
399998,2017-06-13 16:58:51,Kelsey Jones,male,50,G2000,Clothing,16.58
399999,2017-07-05 07:28:44,Kelsey Jones,male,50,"FANCL International, Inc.",Beauty,211.63

In [61]:
names = names[['name', 'salary']]

505621.4327

In [74]:
transaction = transaction.join(names.set_index('name'), on='name')

In [75]:
transaction.to_csv('transaction.csv', index = False)

In [77]:
df = pd.read_csv('transaction.csv')
df

,time,name,gender,age,company name,company label,amount,salary
0,2017-07-02 22:27:48,Rachel Trujillo,male,36,Coursera Inc.,Education,111.22,347740
1,2017-06-10 12:37:05,Rachel Trujillo,male,36,Laura Mercier Cosmetics.,Beauty,108.46,347740
2,2017-06-07 14:24:02,Rachel Trujillo,male,36,Synovus Financial Corp.,Investment,208.21,347740
3,2017-06-25 15:36:22,Rachel Trujillo,male,36,Peak Tramways Company Limited,Transport,222.79,347740
4,2017-06-30 03:34:48,Rachel Trujillo,male,36,McDonald' s,Dining,86.28,347740
5,2017-06-29 18:00:00,Rachel Trujillo,male,36,Pearson plc,Education,47.68,347740
6,2017-06-30 21:34:26,Rachel Trujillo,male,36,Wal-Mart Stores Inc,Grocery,93.69,347740
7,2017-07-04 11:57:56,Rachel Trujillo,male,36,Principal Financial Group Inc,Investment,115.46,347740
8,2017-06-13 06:54:58,Rachel Trujillo,male,36,"Voya Financial, Inc.",Investment,142.11,347740
9,2017-07-02 18:23:56,Rachel Trujillo,male,36,"The Dairy Farm Company, Limited",Grocery,61.87,347740
10,2017-06-17 03:32:26,Rachel Trujillo,male,36,"2U, Inc.",Education,280.35,347740
11,2017-07-03 13:44:19,Rachel Trujillo,male,36,City Super Limited,Grocery,281.82,347740
12,2017-06-16 16:16:17,Rachel Trujillo,male,36,GAP,Clothing,9.13,347740
13,2017-06-17 01:17:02,Rachel Trujillo,male,36,Subway,Dining,104.77,347740
14,2017-06-21 11:14:37,Rachel Trujillo,male,36,"KOKUYO Co.,Ltd.",Stationery,300.88,347740
15,2017-06-11 21:15:08,Rachel Trujillo,male,36,"Raymond James Financial, Inc.",Investment,33.22,347740
16,2017-06-14 11:45:03,Rachel Trujillo,male,36,"KOKUYO Co.,Ltd.",Stationery,297.04,347740
17,2017-07-03 21:29:17,Rachel Trujillo,male,36,Liberty Stationery Corp.,Stationery,133.08,347740
18,2017-06-20 09:04:47,Rachel Trujillo,male,36,Ikari Area,Entertainment,9.43,347740
19,2017-06-10 18:31:22,Rachel Trujillo,male,36,"The 'Star' Ferry Company, Limited",Transport,201.96,347740
20,2017-07-05 20:58:23,Rachel Trujillo,male,36,Tim Ho Wan,Dining,292.67,347740
21,2017-06-23 20:15:43,Rachel Trujillo,male,36,BB Liquidating Inc,Media,163.39,347740
22,2017-06-24 15:32:14,Rachel Trujillo,male,36,Parker Pen Company,Stationery,260.15,347740
23,2017-06-24 04:00:43,Rachel Trujillo,male,36,Le.com,Media,149.06,347740
24,2017-07-04 03:13:19,Rachel Trujillo,male,36,J. Crew,Clothing,273.85,347740
25,2017-06-12 00:30:44,Rachel Trujillo,male,36,"Voya Financial, Inc.",Investment,93.04,347740
26,2017-06-20 09:50:33,Rachel Trujillo,male,36,Neway Karaoke Box Limited,Entertainment,239.05,347740
27,2017-06-22 22:08:41,Rachel Trujillo,male,36,TCF Financial Corporation,Investment,244.24,347740
28,2017-06-11 13:26:35,Rachel Trujillo,male,36,Principal Financial Group Inc,Investment,117.48,347740
29,2017-07-04 09:40:59,Rachel Trujillo,male,36,Laura Mercier Cosmetics.,Beauty,134.45,347740
...,...,...,...,...,...,...,...,...
399970,2017-06-12 23:41:20,Kelsey Jones,male,50,Sumitomo Mitsui Financial Group Inc,Investment,16.89,570823
399971,2017-06-29 22:55:52,Kelsey Jones,male,50,"Udacity, Inc.",Education,197.18,570823
399972,2017-06-08 21:36:12,Kelsey Jones,male,50,Staedtler Mars GmbH & Co. KG,Stationery,81.63,570823
399973,2017-06-07 07:32:09,Kelsey Jones,male,50,"Waddell & Reed Financial, Inc.",Investment,258.03,570823
399974,2017-06-30 10:49:34,Kelsey Jones,male,50,"Shenzhen Comix Stationery Co., Ltd.",Stationery,200.22,570823
399975,2017-06-29 10:25:22,Kelsey Jones,male,50,Hong Kong Dragon Airlines Ltd,Transport,16.32,570823
399976,2017-07-02 23:05:33,Kelsey Jones,male,50,Maxim' s Catering,Dining,265.12,570823
399977,2017-06-14 09:14:25,Kelsey Jones,male,50,Shinhan Financial Group Co Ltd,Investment,113.96,570823
399978,2017-06-16 23:01:34,Kelsey Jones,male,50,The Kowloon Motor Bus Company Limited,Transport,51.15,570823
399979,2017-06-30 20:05:53,Kelsey Jones,male,50,Xbox,Entertainment,233.69,570823
399980,2017-06-14 11:43:47,Kelsey Jones,male,50,J. Crew,Clothing,141.99,570823
399981,2017-06-07 09:19:46,Kelsey Jones,male,50,New World First Bus Services Limited,Transport,197.35,570823
399982,2017-06-28 11:42:38,Kelsey Jones,male,50,edX Inc.,Education,294.94,570823
399983,2017-06-13 14:28:37,Kelsey Jones,male,50,Yadkin Financial Corporation,Investment,52.28,570823
399984,2017-06-17 13:29:12,Kelsey Jones,male,50,"Netflix, Inc.",Media,31.73,570823
399985,2017-06-15 06:16:08,Kelsey Jones,male,50,Ikari Area,Entertainment,201.77,570823
399986,2017-06-23 18:05:50,Kelsey Jones,male,50,Levi Strauss & Co.,Clothing,272.93,570823
399987,2017-06-16 12:47:34,Kelsey Jones,male,50,Spotify AB,Media,114.97,570823
399988,2017-06-22 20:57:56,Kelsey Jones,male,50,Cathay Pacific Airways,Transport,71.12,570823
399989,2017-06-26 04:56:07,Kelsey Jones,male,50,Coursera Inc.,Education,275.30,570823
399990,2017-07-02 17:11:21,Kelsey Jones,male,50,Code School LLC.,Education,92.36,570823
399991,2017-06-16 02:28:35,Kelsey Jones,male,50,Ryze Ultimate Trampoline Park Hong Kong,Entertainment,283.62,570823
399992,2017-07-04 20:10:37,Kelsey Jones,male,50,"Redbox Automated Retail, LLC.",Media,169.40,570823
399993,2017-06-17 02:49:32,Kelsey Jones,male,50,McDonald' s,Dining,55.72,570823
399994,2017-06-28 08:49:46,Kelsey Jones,male,50,Long Win Bus Company Limited,Transport,156.04,570823
399995,2017-07-02 21:33:10,Kelsey Jones,male,50,New Oriental Education & Tech Grp,Education,39.57,570823
399996,2017-06-26 10:09:42,Kelsey Jones,male,50,Xbox,Entertainment,222.35,570823
399997,2017-06-13 04:40:07,Kelsey Jones,male,50,Tim Ho Wan,Dining,163.53,570823
399998,2017-06-13 16:58:51,Kelsey Jones,male,50,G2000,Clothing,16.58,570823
399999,2017-07-05 07:28:44,Kelsey Jones,male,50,"FANCL International, Inc.",Beauty,211.63,570823

In [65]:
df

,time,name,gender,age,company name,company label,amount
0,2017-07-02 22:27:48,Rachel Trujillo,male,36,Coursera Inc.,Education,111.22
1,2017-06-10 12:37:05,Rachel Trujillo,male,36,Laura Mercier Cosmetics.,Beauty,108.46
2,2017-06-07 14:24:02,Rachel Trujillo,male,36,Synovus Financial Corp.,Investment,208.21
3,2017-06-25 15:36:22,Rachel Trujillo,male,36,Peak Tramways Company Limited,Transport,222.79
4,2017-06-30 03:34:48,Rachel Trujillo,male,36,McDonald' s,Dining,86.28
5,2017-06-29 18:00:00,Rachel Trujillo,male,36,Pearson plc,Education,47.68
6,2017-06-30 21:34:26,Rachel Trujillo,male,36,Wal-Mart Stores Inc,Grocery,93.69
7,2017-07-04 11:57:56,Rachel Trujillo,male,36,Principal Financial Group Inc,Investment,115.46
8,2017-06-13 06:54:58,Rachel Trujillo,male,36,"Voya Financial, Inc.",Investment,142.11
9,2017-07-02 18:23:56,Rachel Trujillo,male,36,"The Dairy Farm Company, Limited",Grocery,61.87
10,2017-06-17 03:32:26,Rachel Trujillo,male,36,"2U, Inc.",Education,280.35
11,2017-07-03 13:44:19,Rachel Trujillo,male,36,City Super Limited,Grocery,281.82
12,2017-06-16 16:16:17,Rachel Trujillo,male,36,GAP,Clothing,9.13
13,2017-06-17 01:17:02,Rachel Trujillo,male,36,Subway,Dining,104.77
14,2017-06-21 11:14:37,Rachel Trujillo,male,36,"KOKUYO Co.,Ltd.",Stationery,300.88
15,2017-06-11 21:15:08,Rachel Trujillo,male,36,"Raymond James Financial, Inc.",Investment,33.22
16,2017-06-14 11:45:03,Rachel Trujillo,male,36,"KOKUYO Co.,Ltd.",Stationery,297.04
17,2017-07-03 21:29:17,Rachel Trujillo,male,36,Liberty Stationery Corp.,Stationery,133.08
18,2017-06-20 09:04:47,Rachel Trujillo,male,36,Ikari Area,Entertainment,9.43
19,2017-06-10 18:31:22,Rachel Trujillo,male,36,"The 'Star' Ferry Company, Limited",Transport,201.96
20,2017-07-05 20:58:23,Rachel Trujillo,male,36,Tim Ho Wan,Dining,292.67
21,2017-06-23 20:15:43,Rachel Trujillo,male,36,BB Liquidating Inc,Media,163.39
22,2017-06-24 15:32:14,Rachel Trujillo,male,36,Parker Pen Company,Stationery,260.15
23,2017-06-24 04:00:43,Rachel Trujillo,male,36,Le.com,Media,149.06
24,2017-07-04 03:13:19,Rachel Trujillo,male,36,J. Crew,Clothing,273.85
25,2017-06-12 00:30:44,Rachel Trujillo,male,36,"Voya Financial, Inc.",Investment,93.04
26,2017-06-20 09:50:33,Rachel Trujillo,male,36,Neway Karaoke Box Limited,Entertainment,239.05
27,2017-06-22 22:08:41,Rachel Trujillo,male,36,TCF Financial Corporation,Investment,244.24
28,2017-06-11 13:26:35,Rachel Trujillo,male,36,Principal Financial Group Inc,Investment,117.48
29,2017-07-04 09:40:59,Rachel Trujillo,male,36,Laura Mercier Cosmetics.,Beauty,134.45
...,...,...,...,...,...,...,...
399970,2017-06-12 23:41:20,Kelsey Jones,male,50,Sumitomo Mitsui Financial Group Inc,Investment,16.89
399971,2017-06-29 22:55:52,Kelsey Jones,male,50,"Udacity, Inc.",Education,197.18
399972,2017-06-08 21:36:12,Kelsey Jones,male,50,Staedtler Mars GmbH & Co. KG,Stationery,81.63
399973,2017-06-07 07:32:09,Kelsey Jones,male,50,"Waddell & Reed Financial, Inc.",Investment,258.03
399974,2017-06-30 10:49:34,Kelsey Jones,male,50,"Shenzhen Comix Stationery Co., Ltd.",Stationery,200.22
399975,2017-06-29 10:25:22,Kelsey Jones,male,50,Hong Kong Dragon Airlines Ltd,Transport,16.32
399976,2017-07-02 23:05:33,Kelsey Jones,male,50,Maxim' s Catering,Dining,265.12
399977,2017-06-14 09:14:25,Kelsey Jones,male,50,Shinhan Financial Group Co Ltd,Investment,113.96
399978,2017-06-16 23:01:34,Kelsey Jones,male,50,The Kowloon Motor Bus Company Limited,Transport,51.15
399979,2017-06-30 20:05:53,Kelsey Jones,male,50,Xbox,Entertainment,233.69
399980,2017-06-14 11:43:47,Kelsey Jones,male,50,J. Crew,Clothing,141.99
399981,2017-06-07 09:19:46,Kelsey Jones,male,50,New World First Bus Services Limited,Transport,197.35
399982,2017-06-28 11:42:38,Kelsey Jones,male,50,edX Inc.,Education,294.94
399983,2017-06-13 14:28:37,Kelsey Jones,male,50,Yadkin Financial Corporation,Investment,52.28
399984,2017-06-17 13:29:12,Kelsey Jones,male,50,"Netflix, Inc.",Media,31.73
399985,2017-06-15 06:16:08,Kelsey Jones,male,50,Ikari Area,Entertainment,201.77
399986,2017-06-23 18:05:50,Kelsey Jones,male,50,Levi Strauss & Co.,Clothing,272.93
399987,2017-06-16 12:47:34,Kelsey Jones,male,50,Spotify AB,Media,114.97
399988,2017-06-22 20:57:56,Kelsey Jones,male,50,Cathay Pacific Airways,Transport,71.12
399989,2017-06-26 04:56:07,Kelsey Jones,male,50,Coursera Inc.,Education,275.30
399990,2017-07-02 17:11:21,Kelsey Jones,male,50,Code School LLC.,Education,92.36
399991,2017-06-16 02:28:35,Kelsey Jones,male,50,Ryze Ultimate Trampoline Park Hong Kong,Entertainment,283.62
399992,2017-07-04 20:10:37,Kelsey Jones,male,50,"Redbox Automated Retail, LLC.",Media,169.40
399993,2017-06-17 02:49:32,Kelsey Jones,male,50,McDonald' s,Dining,55.72
399994,2017-06-28 08:49:46,Kelsey Jones,male,50,Long Win Bus Company Limited,Transport,156.04
399995,2017-07-02 21:33:10,Kelsey Jones,male,50,New Oriental Education & Tech Grp,Education,39.57
399996,2017-06-26 10:09:42,Kelsey Jones,male,50,Xbox,Entertainment,222.35
399997,2017-06-13 04:40:07,Kelsey Jones,male,50,Tim Ho Wan,Dining,163.53
399998,2017-06-13 16:58:51,Kelsey Jones,male,50,G2000,Clothing,16.58
399999,2017-07-05 07:28:44,Kelsey Jones,male,50,"FANCL International, Inc.",Beauty,211.63